<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\User;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // Fetch or create certified owner accounts
        $owners = User::where('is_admin', false)->get();
        if ($owners->isEmpty()) {
            $owner1 = User::firstOrCreate(
                ['email' => 'rahul.owner@homiq.space'],
                [
                    'name' => 'Rahul Sharma (Verified Owner)',
                    'password' => bcrypt('password123'),
                    'phone' => '9876543210',
                    'subscription_plan' => 'unlimited',
                    'is_admin' => false,
                    'email_verified_at' => now(),
                ]
            );
            $owner2 = User::firstOrCreate(
                ['email' => 'priya.landlord@homiq.space'],
                [
                    'name' => 'Priya Verma (Property Host)',
                    'password' => bcrypt('password123'),
                    'phone' => '9811223344',
                    'subscription_plan' => 'unlimited',
                    'is_admin' => false,
                    'email_verified_at' => now(),
                ]
            );
            $ownerIds = [$owner1->id, $owner2->id];
        } else {
            $ownerIds = $owners->pluck('id')->toArray();
        }

        $properties = [
            // ── NOIDA (PRIMARY MARKET) ─────────────────────────────────────
            [
                'title' => '2 BHK Semi-Furnished Flat in Paras Tierea',
                'description' => 'Spacious 2BHK flat in Paras Tierea, Sector 137. Walking distance from Sector 137 Metro Station. Features modular kitchen, wooden wardrobes, pool-facing balcony, 24/7 power backup, and gated security.',
                'price' => 24000,
                'security_deposit' => 48000,
                'address' => 'Paras Tierea, Sector 137, Noida, Uttar Pradesh',
                'distance_from_metro' => '250m from Sector 137 Metro',
                'latitude' => 28.5034,
                'longitude' => 77.4056,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null, // Immediate
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 1150,
                'carpet_area' => 950,
                'floor_number' => '8',
                'total_floors' => '19',
                'floor_number' => 8,
                'total_floors' => 19,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => true,
                'amenities' => ['Gated Security', 'Power Backup', 'Gym', 'Swimming Pool', 'Clubhouse', 'Lift', 'Covered Parking'],
                'amenities' => ['Gated Security', 'Power Backup', 'Gym', 'Swimming Pool', 'Clubhouse', 'Lift', 'Covered Parking', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(1),
            ],
            [
                'title' => '3 BHK Furnished Society Flat in Supertech Capetown',
                'description' => 'Bright and airy 3 BHK apartment in Supertech Capetown, Sector 74. Completely furnished with double beds, ACs in all rooms, sofa set, refrigerator, and RO water system. Family-friendly gated township.',
                'price' => 32000,
                'security_deposit' => 64000,
                'address' => 'Supertech Capetown, Sector 74, Noida, Uttar Pradesh',
                'distance_from_metro' => '800m from Sector 76 Metro',
                'latitude' => 28.5833,
                'longitude' => 77.3889,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'built_up_area' => 1500,
                'carpet_area' => 1250,
                'floor_number' => '12',
                'total_floors' => '24',
                'floor_number' => 12,
                'total_floors' => 24,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => true,
                'amenities' => ['AC', 'Modular Kitchen', 'Power Backup', 'Lift', 'Clubhouse', 'Security 24/7', 'Tennis Court'],
                'amenities' => ['AC', 'Modular Kitchen', 'Power Backup', 'Lift', 'Clubhouse', 'Security 24/7', 'Tennis Court', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subHours(6),
            ],
            [
                'title' => '1 BHK Studio Flat near Sector 62 IT Hub',
                'description' => 'Convenient 1 BHK apartment close to Sector 62 Electronic City metro station and major IT campuses. Equipped with high-speed WiFi, split AC, study table, geyser, and dedicated parking.',
                'price' => 15000,
                'security_deposit' => 30000,
                'address' => 'Skyline Apartments, Sector 62, Noida, Uttar Pradesh',
                'distance_from_metro' => '300m from Electronic City Metro',
                'latitude' => 28.6273,
                'longitude' => 77.3714,
                'category' => 'Studio',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'built_up_area' => 650,
                'carpet_area' => 520,
                'floor_number' => '3',
                'total_floors' => '10',
                'floor_number' => 3,
                'total_floors' => 10,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => false,
                'is_featured' => false,
                'amenities' => ['High Speed WiFi', 'AC', 'Geyser', 'Lift', '24/7 Security', 'Power Backup'],
                'amenities' => ['High Speed WiFi', 'AC', 'Geyser', 'Lift', '24/7 Security', 'Power Backup', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
            ],
            [
                'title' => '2 BHK Society Apartment in Express Zenith',
                'description' => 'Well-ventilated 2 BHK apartment in Express Zenith, Sector 77. Corner unit with natural sunlight, spacious balconies, modular kitchen, and covered car parking.',
                'price' => 22000,
                'security_deposit' => 44000,
                'address' => 'Express Zenith, Sector 77, Noida, Uttar Pradesh',
                'distance_from_metro' => '600m from Sector 76 Metro',
                'latitude' => 28.5772,
                'longitude' => 77.3821,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => now()->addDays(10),
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 1075,
                'carpet_area' => 880,
                'floor_number' => '6',
                'total_floors' => '18',
                'floor_number' => 6,
                'total_floors' => 18,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => false,
                'amenities' => ['Covered Parking', 'Gated Community', 'Swimming Pool', 'Gym', 'Power Backup'],
                'images' => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(2),
            ],
            [
                'title' => 'Prime Commercial Retail Shop in Sector 18 Market',
                'description' => 'Ground floor commercial shop in high-footfall Sector 18 commercial market. Ideal for boutique, clinic, cafe, or electronics showroom. Ready with glass facade and power backup.',
                'price' => 45000,
                'security_deposit' => 90000,
                'address' => 'Atta Market, Sector 18, Noida, Uttar Pradesh',
                'distance_from_metro' => '150m from Sector 18 Metro',
                'latitude' => 28.5707,
                'longitude' => 77.3219,
                'category' => 'Shop',
                'listing_type' => 'rent',
                'listed_by' => 'agent',
                'available_from' => null,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'built_up_area' => 420,
                'carpet_area' => 380,
                'floor_number' => 'Ground',
                'total_floors' => '3',
                'floor_number' => 0,
                'total_floors' => 3,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => false,
                'is_featured' => true,
                'amenities' => ['Glass Facade', 'Main Road Facing', 'Power Backup', 'Washroom', 'High Footfall'],
                'amenities' => ['Glass Facade', 'Main Road Facing', 'Power Backup', 'Washroom', 'High Footfall', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(2),
            ],

            // ── GREATER NOIDA & NOIDA EXTENSION ───────────────────────────
            [
                'title' => '2 BHK Family Home in Gaur City 2',
                'description' => 'Modern 2 BHK apartment in Gaur City 2, Noida Extension. Proximity to market, international schools, and Gaur City Mall. Gated security with full power backup.',
                'price' => 17500,
                'security_deposit' => 35000,
                'address' => '14th Avenue, Gaur City 2, Greater Noida West, Uttar Pradesh',
                'distance_from_metro' => 'Direct feeder bus to Noida City Centre',
                'latitude' => 28.6089,
                'longitude' => 77.4332,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 960,
                'carpet_area' => 790,
                'floor_number' => '7',
                'total_floors' => '22',
                'floor_number' => 7,
                'total_floors' => 22,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => true,
                'amenities' => ['Clubhouse', 'Market Inside Complex', 'Power Backup', 'Security', 'Play Area'],
                'images' => [
                    'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(2),
            ],
            [
                'title' => 'Furnished Student PG Room with Meals & WiFi',
                'description' => 'Fully managed AC room for students & working professionals in Knowledge Park III. Includes 3 hygienic meals daily, high-speed WiFi, laundry, housekeeping, and study desks.',
                'price' => 9500,
                'security_deposit' => 9500,
                'address' => 'Knowledge Park III, Greater Noida, Uttar Pradesh',
                'distance_from_metro' => '400m from Knowledge Park II Metro',
                'latitude' => 28.4722,
                'longitude' => 77.4892,
                'category' => 'Studio',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'built_up_area' => 280,
                'carpet_area' => 240,
                'floor_number' => '2',
                'total_floors' => '4',
                'floor_number' => 2,
                'total_floors' => 4,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => false,
                'is_featured' => true,
                'amenities' => ['3 Daily Meals', 'High Speed WiFi', 'AC', 'Housekeeping', 'RO Water', 'CCTV Security'],
                'amenities' => ['3 Daily Meals', 'High Speed WiFi', 'AC', 'Housekeeping', 'RO Water', 'CCTV Security', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(4),
            ],
            [
                'title' => 'Independent 3 BHK Villa in Alpha 1',
                'description' => 'Spacious independent 3 BHK duplex house with front lawn, private terrace, and parking for 2 cars. Located in a quiet, green residential sector close to Pari Chowk.',
                'price' => 28000,
                'security_deposit' => 56000,
                'address' => 'Sector Alpha 1, Greater Noida, Uttar Pradesh',
                'distance_from_metro' => '500m from Alpha 1 Metro',
                'latitude' => 28.4754,
                'longitude' => 77.5032,
                'category' => 'House',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => now()->addDays(5),
                'bedrooms' => 3,
                'bathrooms' => 3,
                'built_up_area' => 2100,
                'carpet_area' => 1800,
                'floor_number' => 'Ground + 1',
                'total_floors' => '2',
                'floor_number' => 1,
                'total_floors' => 2,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => false,
                'amenities' => ['Private Garden', 'Terrace', 'Car Porch', 'Borewell & Municipal Water', 'Gated Sector'],
                'amenities' => ['Private Garden', 'Terrace', 'Car Porch', 'Borewell & Municipal Water', 'Gated Sector', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(3),
            ],

            // ── GURUGRAM ──────────────────────────────────────────────────
            [
                'title' => '1 RK Furnished Studio near Cyber City',
                'description' => 'Chic furnished 1 RK studio in DLF Phase 3 near Moulsari Avenue Rapid Metro station. Includes AC, smart TV, kitchen counter with induction, fridge, and power backup.',
                'price' => 19000,
                'security_deposit' => 38000,
                'address' => 'U Block, DLF Phase 3, Gurugram, Haryana',
                'distance_from_metro' => '300m from Moulsari Ave Rapid Metro',
                'latitude' => 28.4986,
                'longitude' => 77.0945,
                'category' => 'Studio',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'built_up_area' => 450,
                'carpet_area' => 380,
                'floor_number' => '3',
                'total_floors' => '5',
                'floor_number' => 3,
                'total_floors' => 5,
                'is_furnished' => true,
                'has_parking' => false,
                'is_pet_friendly' => false,
                'is_featured' => true,
                'amenities' => ['AC', 'Smart TV', 'Fridge', 'WiFi', 'Power Backup', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(5),
                'updated_at' => now()->subHours(1),
            ],
            [
                'title' => '3 BHK Luxury Flat on Golf Course Extension Road',
                'description' => 'Premium 3 BHK society flat with modular kitchen, Italian marble, servant quarter, and club amenities. Excellent road connectivity to Cyber Hub and Golf Course Road.',
                'price' => 48000,
                'security_deposit' => 96000,
                'address' => 'Sector 56, Golf Course Extension, Gurugram, Haryana',
                'distance_from_metro' => '450m from Sector 56 Metro',
                'latitude' => 28.4285,
                'longitude' => 77.1025,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => now()->addDays(15),
                'bedrooms' => 3,
                'bathrooms' => 3,
                'built_up_area' => 1850,
                'carpet_area' => 1550,
                'floor_number' => '14',
                'total_floors' => '26',
                'floor_number' => 14,
                'total_floors' => 26,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => false,
                'amenities' => ['Modular Kitchen', 'Clubhouse', 'Swimming Pool', 'Gym', 'Covered Parking', 'Lift'],
                'amenities' => ['Modular Kitchen', 'Clubhouse', 'Swimming Pool', 'Gym', 'Covered Parking', 'Lift', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(4),
            ],

            // ── DELHI ─────────────────────────────────────────────────────
            [
                'title' => '2 BHK Builder Floor in Hauz Khas',
                'description' => 'Elegant 2 BHK independent builder floor in Hauz Khas. Features modular kitchen, wooden wardrobes, attached washrooms, and lift access with dedicated car parking.',
                'price' => 36000,
                'security_deposit' => 72000,
                'address' => 'Hauz Khas Enclave, South Delhi, Delhi',
                'distance_from_metro' => '400m from Hauz Khas Metro',
                'latitude' => 28.5494,
                'longitude' => 77.2001,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'agent',
                'available_from' => null,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 1100,
                'carpet_area' => 920,
                'floor_number' => '2',
                'total_floors' => '4',
                'floor_number' => 2,
                'total_floors' => 4,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => false,
                'amenities' => ['Lift', 'Dedicated Parking', 'Modular Kitchen', 'Balcony', 'Gated Colony'],
                'amenities' => ['Lift', 'Dedicated Parking', 'Modular Kitchen', 'Balcony', 'Gated Colony', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subHours(18),
            ],
            [
                'title' => 'Student PG Room near Metro in Laxmi Nagar',
                'description' => 'Budget friendly single/double occupancy PG accommodation for students and CA aspirants. Walking distance from Laxmi Nagar Metro Station. 24hr water and WiFi.',
                'price' => 7500,
                'security_deposit' => 7500,
                'address' => 'Vikas Marg, Laxmi Nagar, East Delhi, Delhi',
                'distance_from_metro' => '150m from Laxmi Nagar Metro',
                'latitude' => 28.6306,
                'longitude' => 77.2773,
                'category' => 'Studio',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'built_up_area' => 220,
                'carpet_area' => 190,
                'floor_number' => '2',
                'total_floors' => '4',
                'floor_number' => 2,
                'total_floors' => 4,
                'is_furnished' => true,
                'has_parking' => false,
                'is_pet_friendly' => false,
                'is_featured' => false,
                'amenities' => ['WiFi', 'RO Water', 'Geyser', 'Near Metro', 'Bed & Almirah'],
                'images' => [
                    'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(16),
                'updated_at' => now()->subHours(8),
            ],

            // ── BANGALORE ─────────────────────────────────────────────────
            [
                'title' => '2 BHK Modern Flat in HSR Layout',
                'description' => 'Stylishly designed 2 BHK flat in HSR Layout Sector 2. Located close to tech startups, cafes, and supermarkets. Ideal for software engineers and young families.',
                'price' => 28000,
                'security_deposit' => 100000,
                'address' => '27th Main, HSR Layout Sector 2, Bangalore, Karnataka',
                'distance_from_metro' => '1.2 km from Silk Board Metro',
                'latitude' => 12.9141,
                'longitude' => 77.6501,
                'category' => 'Apartment',
                'listing_type' => 'rent',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 1180,
                'carpet_area' => 980,
                'floor_number' => '3',
                'total_floors' => '5',
                'floor_number' => 3,
                'total_floors' => 5,
                'is_furnished' => true,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => true,
                'amenities' => ['Lift', 'Covered Parking', 'Balcony', 'Power Backup', 'CCTV'],
                'images' => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subHours(20),
                'updated_at' => now()->subHours(5),
            ],

            // ── PROPERTIES FOR SALE (NOIDA / GREATER NOIDA) ───────────────
            [
                'title' => '3 BHK Society Apartment for Sale in Mahagun Moderne',
                'description' => 'Ready to move 3 BHK luxury apartment in Mahagun Moderne, Sector 78. Freehold registry, RERA approved, high floor with unobstructed garden view.',
                'price' => 13500000,
                'security_deposit' => 0,
                'address' => 'Mahagun Moderne, Sector 78, Noida, Uttar Pradesh',
                'distance_from_metro' => '350m from Sector 76 Metro',
                'latitude' => 28.5682,
                'longitude' => 77.3871,
                'category' => 'Apartment',
                'listing_type' => 'sale',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'built_up_area' => 1650,
                'carpet_area' => 1380,
                'floor_number' => '15',
                'total_floors' => '25',
                'floor_number' => 15,
                'total_floors' => 25,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => true,
                'ownership_type' => 'Freehold',
                'is_rera_approved' => true,
                'amenities' => ['Clubhouse', 'Olympic Pool', 'Tennis Court', 'Reserved Parking', 'Security'],
                'amenities' => ['Clubhouse', 'Olympic Pool', 'Tennis Court', 'Reserved Parking', 'Security', 'Near Metro'],
                'images' => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subHours(10),
            ],
            [
                'title' => '2 BHK Society Flat for Sale in Gaur City 1',
                'description' => 'Affordable and well-maintained 2 BHK apartment for sale in Gaur City 1. Bank loan approved from all major PSU & private banks.',
                'price' => 5800000,
                'security_deposit' => 0,
                'address' => 'Gaur City 1, Noida Extension, Greater Noida West, Uttar Pradesh',
                'distance_from_metro' => 'Upcoming Gaur City Metro Station',
                'latitude' => 28.6142,
                'longitude' => 77.4265,
                'category' => 'Apartment',
                'listing_type' => 'sale',
                'listed_by' => 'owner',
                'available_from' => null,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'built_up_area' => 1020,
                'carpet_area' => 860,
                'floor_number' => '9',
                'total_floors' => '20',
                'floor_number' => 9,
                'total_floors' => 20,
                'is_furnished' => false,
                'has_parking' => true,
                'is_pet_friendly' => true,
                'is_featured' => false,
                'ownership_type' => 'Freehold',
                'is_rera_approved' => true,
                'amenities' => ['Park Facing', 'Gated Society', 'Power Backup', 'Gym'],
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'
                ],
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(1),
            ],
        ];

        foreach ($properties as $index => $prop) {
            $ownerId = $ownerIds[$index % count($ownerIds)];
            Property::create(array_merge($prop, [
                'owner_id' => $ownerId,
                'status' => 'approved',
                'currency' => 'INR',
                'billing_frequency' => 'monthly',
                'country' => 'India',
                'verified_at' => now()->subDays(random_int(1, 5)),
                'expires_at' => now()->addDays(random_int(25, 30)),
                'last_renewed_at' => now()->subDays(random_int(1, 5)),
                'is_identity_verified' => true,
                'is_location_verified' => true,
                'is_photos_verified' => true,
                'is_ownership_verified' => true,
                'verifier_notes' => 'On-site inspected and physical title documents verified by HomiQ audit team',
                'views_count' => random_int(45, 230),
                'impressions_count' => random_int(300, 1200),
                'inquiries_count' => random_int(4, 18),
                'whatsapp_clicks' => random_int(3, 14),
                'saves_count' => random_int(6, 32),
            ]));
        }
    }
}
