<?php

namespace Database\Seeders;

use App\Models\PropertyRequest;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertyRequestSeeder extends Seeder
{
    public function run(): void
    {
        $renter = User::where('email', 'renter@example.com')->first();
        $renterId = $renter?->id;

        $requests = [
            // ── NOIDA REQUESTS ──────────────────────────────────────────
            [
                'user_id' => $renterId,
                'seeker_name' => 'Aditi Sengupta',
                'seeker_phone' => '9811223344',
                'seeker_email' => 'aditi.tech@example.com',
                'city' => 'Noida',
                'locality' => 'Sector 137',
                'property_type' => 'Apartment',
                'bedrooms' => '2 BHK',
                'min_budget' => 20000,
                'max_budget' => 26000,
                'purpose' => 'rent',
                'move_in_date' => 'Within 15 days',
                'tenant_type' => 'Working Professional',
                'furnishing_preference' => 'Semi-Furnished',
                'description' => 'Senior software engineer at Noida Expressway IT park. Looking for a clean 2 BHK flat in Paras Tierea or Ecociti with balcony and parking.',
                'status' => 'active',
                'responses_count' => 3,
                'created_at' => now()->subHours(2),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Vikram & Sneha Malhotra',
                'seeker_phone' => '9822334455',
                'seeker_email' => 'vikram.m@example.com',
                'city' => 'Noida',
                'locality' => 'Sector 150',
                'property_type' => 'Apartment',
                'bedrooms' => '3 BHK',
                'min_budget' => 32000,
                'max_budget' => 40000,
                'purpose' => 'rent',
                'move_in_date' => 'Next Month',
                'tenant_type' => 'Family',
                'furnishing_preference' => 'Semi-Furnished',
                'description' => 'Family with 1 kid looking for green society with clubhouse, tennis court, and power backup in Sector 150 Noida.',
                'status' => 'active',
                'responses_count' => 5,
                'created_at' => now()->subHours(5),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Rohan Bansal',
                'seeker_phone' => '9833445566',
                'seeker_email' => 'rohan.b@example.com',
                'city' => 'Noida',
                'locality' => 'Sector 62',
                'property_type' => 'Apartment',
                'bedrooms' => '1 BHK',
                'min_budget' => 14000,
                'max_budget' => 18000,
                'purpose' => 'rent',
                'move_in_date' => 'Immediate',
                'tenant_type' => 'Working Professional',
                'furnishing_preference' => 'Furnished',
                'description' => 'Looking for a 1 BHK studio near Electronic City metro station. Ready to move immediately.',
                'status' => 'active',
                'responses_count' => 2,
                'created_at' => now()->subHours(8),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Kavya Sharma',
                'seeker_phone' => '9844556677',
                'seeker_email' => 'kavya.s@example.com',
                'city' => 'Noida',
                'locality' => 'Sector 125',
                'property_type' => 'Studio',
                'bedrooms' => 'Room',
                'min_budget' => 8000,
                'max_budget' => 12000,
                'purpose' => 'rent',
                'move_in_date' => 'Immediate',
                'tenant_type' => 'Student',
                'furnishing_preference' => 'Furnished',
                'description' => 'Amity student looking for a safe, verified girls PG / private room with Wi-Fi and food amenities near Sector 125.',
                'status' => 'active',
                'responses_count' => 4,
                'created_at' => now()->subDay(),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Rajeev Mathur (Buyer)',
                'seeker_phone' => '9855667788',
                'seeker_email' => 'rajeev.invest@example.com',
                'city' => 'Noida',
                'locality' => 'Sector 75',
                'property_type' => 'Apartment',
                'bedrooms' => '3 BHK',
                'min_budget' => 9000000,
                'max_budget' => 14000000,
                'purpose' => 'buy',
                'move_in_date' => 'Within 30 days',
                'tenant_type' => 'Family',
                'furnishing_preference' => 'Any',
                'description' => 'Serious buyer looking for 3 BHK high-rise flat in Sector 75 / 76 Noida. Direct owners only, ready with pre-approved home loan.',
                'status' => 'active',
                'responses_count' => 6,
                'created_at' => now()->subDays(2),
            ],

            // ── GREATER NOIDA ──────────────────────────────────────────
            [
                'user_id' => $renterId,
                'seeker_name' => 'Amitabh Saxena',
                'seeker_phone' => '9866778899',
                'seeker_email' => 'amitabh.saxena@example.com',
                'city' => 'Greater Noida',
                'locality' => 'Gaur City 2',
                'property_type' => 'Apartment',
                'bedrooms' => '2 BHK',
                'min_budget' => 14000,
                'max_budget' => 18000,
                'purpose' => 'rent',
                'move_in_date' => 'Within 15 days',
                'tenant_type' => 'Family',
                'furnishing_preference' => 'Semi-Furnished',
                'description' => 'Looking for 2 BHK in Gaur City 1/2 or Noida Extension. Need gated society with parking and school bus access.',
                'status' => 'active',
                'responses_count' => 4,
                'created_at' => now()->subHours(6),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Manish Choudhary',
                'seeker_phone' => '9877889900',
                'seeker_email' => 'manish.choudhary@example.com',
                'city' => 'Greater Noida',
                'locality' => 'Knowledge Park 3',
                'property_type' => 'Studio',
                'bedrooms' => 'Room',
                'min_budget' => 7000,
                'max_budget' => 10000,
                'purpose' => 'rent',
                'move_in_date' => 'Immediate',
                'tenant_type' => 'Student',
                'furnishing_preference' => 'Furnished',
                'description' => 'Engineering student looking for a shared room or twin-sharing PG near Knowledge Park metro station.',
                'status' => 'active',
                'responses_count' => 2,
                'created_at' => now()->subHours(12),
            ],

            // ── GURUGRAM & DELHI ───────────────────────────────────────
            [
                'user_id' => $renterId,
                'seeker_name' => 'Dev Innovations Pvt Ltd',
                'seeker_phone' => '9888990011',
                'seeker_email' => 'office@devinnovations.com',
                'city' => 'Gurugram',
                'locality' => 'Cyber City',
                'property_type' => 'Commercial',
                'bedrooms' => 'Any',
                'min_budget' => 60000,
                'max_budget' => 95000,
                'purpose' => 'rent',
                'move_in_date' => 'Within 30 days',
                'tenant_type' => 'Company',
                'furnishing_preference' => 'Furnished',
                'description' => 'Looking for 1,200–2,000 sqft plug-and-play furnished office space with 15–20 workstations near Rapid Metro.',
                'status' => 'active',
                'responses_count' => 3,
                'created_at' => now()->subDays(1),
            ],
            [
                'user_id' => $renterId,
                'seeker_name' => 'Dr. Harish & Shweta Gupta',
                'seeker_phone' => '9899001122',
                'seeker_email' => 'harish.gupta@example.com',
                'city' => 'Delhi',
                'locality' => 'South Extension',
                'property_type' => 'House',
                'bedrooms' => '3 BHK',
                'min_budget' => 40000,
                'max_budget' => 55000,
                'purpose' => 'rent',
                'move_in_date' => 'Immediate',
                'tenant_type' => 'Family',
                'furnishing_preference' => 'Semi-Furnished',
                'description' => 'Doctor couple looking for an independent floor or quiet builder floor with dedicated car parking in South Delhi.',
                'status' => 'active',
                'responses_count' => 4,
                'created_at' => now()->subHours(4),
            ],

            // ── BANGALORE ──────────────────────────────────────────────
            [
                'user_id' => $renterId,
                'seeker_name' => 'Nikhil Hegde',
                'seeker_phone' => '9810112233',
                'seeker_email' => 'nikhil.hegde@example.com',
                'city' => 'Bangalore',
                'locality' => 'HSR Layout',
                'property_type' => 'Apartment',
                'bedrooms' => '2 BHK',
                'min_budget' => 28000,
                'max_budget' => 35000,
                'purpose' => 'rent',
                'move_in_date' => 'Immediate',
                'tenant_type' => 'Working Professional',
                'furnishing_preference' => 'Furnished',
                'description' => 'Product Designer at fintech startup looking for a 2 BHK in HSR Sector 2 or 3. Need high-speed fiber internet and power backup.',
                'status' => 'active',
                'responses_count' => 7,
                'created_at' => now()->subHours(3),
            ],
        ];

        foreach ($requests as $req) {
            PropertyRequest::create($req);
        }
    }
}

